### ISSUE TITLE
Call to a member function extend() on a non-object

### ISSUE THREAD

**Issue by chanchal1987** [davidgenetic/cockpit-twig#1]
I am getting below error while trying to use this adon.

```
Fatal error: Call to a member function extend() on a non-object in <COCKPIT_DIR>/modules/addons/cockpit-twig-master/bootstrap.php on line 5
```

**Comment by Mirodil** [comment]
+1

**Comment by davidmaneuver** [comment]
Be sure to unzip the package in a folder called twig. So the full path to the bootstrap file would be 'your_cockpit_folder/modules/addons/twig/bootstrap.php'.

I've updated the readme so this is clear. See 7758af2e6f7f1f9aa00e5176d85b926c13ea9d8a

Does that solve the error?

**Comment by kamwing** [comment]
@davidgenetic Still not working...

**Comment by davidmaneuver** [comment]
Still the same error?
