### ISSUE TITLE
Sort collection items

### ISSUE THREAD

**Issue by vdaguenet** [davidgenetic/cockpit-twig#2]
Hello ! 

I'm trying your Cockpit addon for the first time and I do not find the way to sort items of my collection. I'd like to do 

``` php
collection('posts', {public: 1}, {created: 1}, true)
```

 to achieve this query: 

``` php
  <?php $items = collection("posts")->find(["public"=>true])->sort(["created"=>1])->toArray(); ?>
```

**Comment by davidmaneuver** [comment]
Hi.

Looks like sorting a collection is a feature that was added after I wrote the addon... Or I didn't need at the time.

So it is currently not supported.

You could write your own twig function.

```
new Twig_SimpleFunction('sorted_collection', function($name, $query = [], $sorting = [], $array = true){
  $items = collection($name)->find($query);
  if ($sorting) $items = $items->sort($sorting);
  return $array ? $items->toArray() : $items;
});
```

(I didn't test this)

See http://twig.sensiolabs.org/doc/advanced.html#functions for more info on how to extend Twig.

**Comment by davidmaneuver** [comment]
Feel free to create a pull request, I'll merge it in.

**Comment by vdaguenet** [comment]
It's what I done in my fork. 
I think I will implement `limit` and `skip` too and then make a pull request
